Use lack of rest arg as evidence
During an experiment to require all poly vars to be selected during type
inference I encountered this error:

```
error: cannot determine type of type variable `T` in this context
  --> ./tests/eval-pass/list.arret:47:18
   |
47 |   (assert-eq '() (concat))
   |                  ^^^^^^^^
```

On `master` this instead infers the type of `Any` for `T` which while
correct isn't well constrained.

We can fix this with two changes:

1. During type inference we can use an empty list as evidence for the
   rest type even if there wasn't a rest expression at the apply.

2. Whenever a never type is used as evidence type we should propagate
   the never type in to any collections. This is needed because
   `(concat)` takes a list of lists.